"""Generate the Inno preprocessor values embedded in the uninstaller.

The editable source remains fronts/desktop/links.py.  The generated include
lets Inno compile the same values into unins*.exe, so uninstall does not need
to read application files that may already be missing.
"""

import argparse
import runpy
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LINKS_PATH = ROOT / "fronts" / "desktop" / "links.py"
OUTPUT_PATH = ROOT / "installer" / "farewell-data.iss"

SOURCE_TO_DEFINE = (
    ("ISSUE_URL", "FarewellIssueUrl"),
    ("SUPPORT_MONO_UAH", "FarewellSupportMonoUah"),
    ("SUPPORT_PRIVAT_USD", "FarewellSupportPrivatUsd"),
    ("SUPPORT_PRIVAT_EUR", "FarewellSupportPrivatEur"),
    ("SUPPORT_USDT_TRC20", "FarewellSupportUsdtTrc20"),
    ("SUPPORT_BTC", "FarewellSupportBtc"),
    ("SUPPORT_ETH", "FarewellSupportEth"),
)


def load_source(path=LINKS_PATH):
    values = runpy.run_path(str(path))
    return {name: values[name] for name, _define in SOURCE_TO_DEFINE}


def render_include(values):
    lines = [
        "; Generated by scripts/generate_installer_farewell_data.py.",
        "; Source of truth: fronts/desktop/links.py. Do not edit by hand.",
        "",
    ]
    for source_name, define_name in SOURCE_TO_DEFINE:
        value = values[source_name]
        if not isinstance(value, str) or '"' in value or "\n" in value:
            raise ValueError(f"{source_name} is not a safe one-line ISPP value")
        lines.append(f'#define {define_name} "{value}"')
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting when the generated include is stale",
    )
    args = parser.parse_args(argv)
    expected = render_include(load_source())
    if args.check:
        actual = (
            OUTPUT_PATH.read_text(encoding="utf-8")
            if OUTPUT_PATH.exists()
            else ""
        )
        if actual != expected:
            parser.error(
                "installer/farewell-data.iss is stale; run this script"
            )
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
