; Generated by scripts/generate_installer_farewell_data.py.
; Source of truth: fronts/desktop/links.py. Do not edit by hand.

#define FarewellIssueUrl "https://github.com/mykola-zhukovets/balachky/issues/new"
#define FarewellSupportMonoUah "https://send.monobank.ua/jar/21rfey7KTz"
#define FarewellSupportPrivatUsd "https://www.privat24.ua/send/4h4jh"
#define FarewellSupportPrivatEur "https://www.privat24.ua/send/4h5jr"
#define FarewellSupportUsdtTrc20 "TTsc47PDTe2rUkeXcZGTQwR6driykkP2s8"
#define FarewellSupportBtc "bc1q8wqskryef3ey09jxhv9epdv7kpxnzg8vcf40hy"
#define FarewellSupportEth "0x6A9FeF1CB66C20D31f770a970F790aFC85243A57"
